version: "3.9"
services:
  task-tracker-db:
    image: "official/mongo:8.2.1"
    networks:
      - backend
    volumes:
      - task-tracker-mongodb:/data/db
    healthcheck:
      start_period: 10s
      test: ["CMD", "mongosh", "--norc", "--quiet", "--host=localhost:27017", "--eval", "\"db.getMongo()\""]
      retries: 3
      timeout: 5s
      interval: 10s
  task-tracker-backend:
    image: "task-tracker/task-tracker-backend:local"
    networks:
      - backend
      - frontend
    secrets:
      - task-tracker-backend-env
    environment:
      - ENV_FILE=/run/secrets/task-tracker-backend-env
    depends_on:
      - task-tracker-db
    init: true
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]
      retries: 3
      timeout: 10s
      interval: 60s
      start_period: 30s
  task-tracker-frontend:
    image: "task-tracker/task-tracker-frontend:local-attached"
    networks:
      - frontend
    ports:
      - 5173:5173
    depends_on:
      - task-tracker-db
    init: true
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5173/"]
      interval: 30s
      retries: 3
      timeout: 5s
      start_period: 20s
networks:
  backend:
  frontend:
volumes:
  task-tracker-mongodb:
secrets:
  task-tracker-backend-env:
    external: true
