FROM node:18-alpine AS builder

WORKDIR /todolist

COPY ./todolist-frontend/package.json ./frontend/package.json

COPY ./todolist-backend/package*.json ./backend/

WORKDIR /todolist/frontend

RUN --mount=type=cache,target=/todolist/frontend/.npm \
    npm set cache /todolist/frontend/.npm && \
    npm install

WORKDIR /todolist/backend

RUN --mount=type=cache,target=/todolisit/backend/.npm \
    npm set cache /todolist/backend/.npm && \
    npm ci --only=production

WORKDIR /todolist/frontend/

COPY todolist-frontend/ ./

RUN npm run build:render

WORKDIR /todolist/backend

COPY todolist-backend/ ./



FROM nginx:alpine AS render

RUN apk add --no-cache nodejs-current 

COPY --link --from=builder /todolist/frontend/render/ /usr/share/nginx/html/

COPY --link --from=builder /todolist/backend /todolist-backend

COPY render-nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /todolist-backend

EXPOSE 80

ENV ENV_FILE=".env.render"

CMD ["sh", "-c", "nginx & node src/index.js"]
